[build]
builder = "nixpacks"
buildCommand = "composer install --no-dev"

[deploy]
startCommand = "php artisan config:cache && php artisan route:cache && php artisan view:cache && php artisan migrate --force && php -d display_errors=1 -d error_reporting=E_ALL -S 0.0.0.0:$PORT -t public"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicy = "always"

[env]
APP_ENV = "production"
APP_DEBUG = "true"
LOG_LEVEL = "debug"
APP_URL = "https://${RAILWAY_PUBLIC_DOMAIN}"
LOG_CHANNEL = "stderr"
